#%RAML 1.0 Library
annotationTypes:
  MyFavoriteAnnotation: string
types:
  Url:
    minLength: 2
    pattern: dddd
    example: "dddd"
  Person:
    description: Single Person
    properties:
      name: string
      lastName: string
  Group:
    description: Group of People
    properties:
      name:
        type: string
        description: |
          uniquie identifier of the property
        minLength: 4
        maxLength: 5
        default: "dddd"
      members?: Person[]
  BigGroup:
    type: [ Person, Group]
    properties:
      subGroups: (Group | BigGroup [] | number)[]
      fff:
        properties:
          x: number
          y: number
          mmm:
            properties:
              zzz: number
      another:
        type: array
        items:
          properties:
            d: Url
            x: Person
    patternProperties:
      'dde': string
